void GraphicsControl::addGui(tgui::Gui *gui) {
    tgui::Button::Ptr closeButton(*gui);
    closeButton->load(THEME_CONFIG_FILE);
    closeButton->setPosition(30, lowest + diff * 9);
    closeButton->setSize(60, 20);
    closeButton->setText("Close");
    closeButton->bindCallback(tgui::Button::LeftMouseClicked);
    closeButton->setCallbackId(10);
    tgui::Button::Ptr focusButton(*gui);
    focusButton->load(THEME_CONFIG_FILE);
    focusButton->setPosition(500, 70);
    focusButton->setSize(90, 20);
    focusButton->setText("Focus on Ant");
    focusButton->bindCallback(tgui::Button::LeftMouseClicked);
    focusButton->setCallbackId(13);
    focusAntButton = focusButton;
    tgui::Label::Ptr infoLabel(*gui);
    infoLabel->load(THEME_CONFIG_FILE);
    infoLabel->setPosition(20, 130);
    infoLabel->setTextSize(12);
    infoLabel->setTextColor(sf::Color(20, 200, 200) );
    infoLabel->setText("Info:\n\nIndex:\nX:\nY:\n\nFood:");
    TileInfoLabel = infoLabel;
    tgui::Label::Ptr antLabel(*gui);
    antLabel->load(THEME_CONFIG_FILE);
    antLabel->setPosition(100, 30);
    antLabel->setTextSize(12);
    antLabel->setTextColor(sf::Color(20, 200, 200) );
    antLabel->setText("AntInfo: ...");
    AntInfoLabel = antLabel;
    tgui::Button::Ptr buttonChangeWallUp(*gui);
    buttonChangeWallUp->load(THEME_CONFIG_FILE);
    buttonChangeWallUp->setPosition(15, lowest + diff * 2);
    buttonChangeWallUp->setSize(90, 20);
    buttonChangeWallUp->bindCallback(tgui::Button::LeftMouseClicked);
    buttonChangeWallUp->setCallbackId(0);
    buttonChangeWallUp->setText("ChangeWallsUp");
    tgui::Button::Ptr buttonChangeWallRight(*gui);
    buttonChangeWallRight->load(THEME_CONFIG_FILE);
    buttonChangeWallRight->setSize(90, 20);
    buttonChangeWallRight->setPosition(15, lowest + diff * 3);
    buttonChangeWallRight->bindCallback(tgui::Button::LeftMouseClicked);
    buttonChangeWallRight->setCallbackId(1);
    buttonChangeWallRight->setText("ChangeWallRight");
    tgui::Button::Ptr buttonChangeWallDown(*gui);
    buttonChangeWallDown->load(THEME_CONFIG_FILE);
    buttonChangeWallDown->setSize(90, 20);
    buttonChangeWallDown->setPosition(15, lowest + diff * 4);
    buttonChangeWallDown->bindCallback(tgui::Button::LeftMouseClicked);
    buttonChangeWallDown->setCallbackId(2);
    buttonChangeWallDown->setText("ChangeWallDown");
    tgui::Button::Ptr buttonChangeWallLeft(*gui);
    buttonChangeWallLeft->load(THEME_CONFIG_FILE);
    buttonChangeWallLeft->setSize(90, 20);
    buttonChangeWallLeft->setPosition(15, lowest + diff * 5);
    buttonChangeWallLeft->bindCallback(tgui::Button::LeftMouseClicked);
    buttonChangeWallLeft->setCallbackId(3);
    buttonChangeWallLeft->setText("ChangeWallLeft");
    tgui::Button::Ptr startTicksButton(*gui);
    startTicksButton->load(THEME_CONFIG_FILE);
    startTicksButton->setSize(90, 20);
    startTicksButton->setPosition(500, 40);
    startTicksButton->setCallbackId(4);
    startTicksButton->bindCallback(tgui::Button::LeftMouseClicked);
    startTicksButton->setText("Start");
    ticksControl = startTicksButton;
    tgui::Checkbox::Ptr checkBox(*gui);
    checkBox->load(THEME_CONFIG_FILE);
    checkBox->setPosition(15, lowest + 20);
    checkBox->setText("Moving");
    checkBox->setSize(20, 20);
    checkBox->check();
    advancedMode = checkBox;
    tgui::Button::Ptr setHomeButton(*gui);
    setHomeButton->load(THEME_CONFIG_FILE);
    setHomeButton->setPosition(15, lowest + diff * 6);
    setHomeButton->setText("set Home");
    setHomeButton->setCallbackId(6);
    setHomeButton->bindCallback(tgui::Button::LeftMouseClicked);
    setHomeButton->setSize(90, 20);
    GraphicsControl::setHomeButton = setHomeButton;
    tgui::Button::Ptr setResButton(*gui);
    setResButton->load(THEME_CONFIG_FILE);
    setResButton->setPosition(15, lowest + diff * 7);
    setResButton->setSize(90, 20);
    setResButton->setText("set Resource");
    setResButton->setCallbackId(12);
    setResButton->bindCallback(tgui::Button::LeftMouseClicked);
    GraphicsControl::setResButton = setResButton;
    tgui::Button::Ptr TestConnectedButton(*gui);
    TestConnectedButton->load(THEME_CONFIG_FILE);
    TestConnectedButton->setPosition(15, lowest + diff * 8);
    TestConnectedButton->setText("TestConnected");
    TestConnectedButton->setCallbackId(5);
    TestConnectedButton->bindCallback(tgui::Button::LeftMouseClicked);
    TestConnectedButton->setSize(90, 20);
    tgui::Slider::Ptr slider(*gui);
    slider->load(THEME_CONFIG_FILE);
    slider->setVerticalScroll(false);
    slider->setPosition(20, lowest);
    slider->setSize(80, 11);
    slider->setMinimum(0);
    slider->setMaximum(20);
    slider->setValue(0);
    slider->bindCallback(tgui::Slider::ValueChanged);
    slider->setCallbackId(7);
    GraphicsControl::slider = slider;
    tgui::MenuBar::Ptr menu(*gui);
    menu->load(THEME_CONFIG_FILE);
    menu->setSize(window->getSize().x, 20);
    menu->addMenu("Maze");
    menu->addMenuItem("Maze", "Reset");
    menu->addMenuItem("Maze", "Create Random");
    menu->addMenuItem("Maze", "Create Perfect");
    menu->addMenu("File");
    menu->addMenuItem("File", "Load");
    menu->addMenuItem("File", "Save");
    menu->addMenuItem("File", "Exit");
    menu->bindCallback(tgui::MenuBar::MenuItemClicked);
    menu->setCallbackId(11);
}

/*
LOCtot = 178
LOCne = 136
LOCpars = 120

*/
